# Generated by Django 3.1.5 on 2021-02-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dictentry_userentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DictEntry',
        ),
        migrations.DeleteModel(
            name='UserEntry',
        ),
    ]
